/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Pantallas;

import clases.Datos;

/**
 *
 * @author joelfc
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public FrmPrincipal() {
        initComponents();
        mnuUserCtrl.setVisible(false);  
        mnuPacientes.setVisible(false);
        mnuFarmacia.setVisible(false);
        mnuBenefactores.setVisible(false);
        mnuInventario.setVisible(false);
        mnuCtrlEnf.setVisible(false);
        /*
        if(Datos.modPac>0)
          mnuPacientes.setVisible(true);
        if(Datos.modFarm>0)
           mnuFarmacia.setVisible(true);
        if(Datos.modbenefa>0)
        mnuBenefactores.setVisible(true);
        if(Datos.modInventario>0)
           mnuInventario.setVisible(true);
        if(Datos.modControlEnf>0)
            mnuCtrlEnf.setVisible(true);
        if(Datos.modUsuarios>0)
         mnuUserCtrl.setVisible(true);
        
        */
          
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuPacientes = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        mnuFarmacia = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        mnuCtrlEnf = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        mnuBenefactores = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        mnuInventario = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        mnuUsuarios = new javax.swing.JMenu();
        mnuUserCtrl = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setText("Sistema Avicola");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 490, 100));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 0));
        jLabel3.setText("Módulo Administrativo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1050, 890));

        jMenuBar1.setAlignmentY(10.0F);
        jMenuBar1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N

        mnuPacientes.setText("Pacientes");
        mnuPacientes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jMenuItem2.setText("Control");
        mnuPacientes.add(jMenuItem2);

        jMenuItem3.setText("Responsables");
        mnuPacientes.add(jMenuItem3);

        jMenuItem4.setText("Reportes");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        mnuPacientes.add(jMenuItem4);

        jMenuBar1.add(mnuPacientes);

        mnuFarmacia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mnuFarmacia.setText("Farmacia");
        mnuFarmacia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mnuFarmacia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jMenuItem5.setText("Entradas");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        mnuFarmacia.add(jMenuItem5);

        jMenuItem6.setText("Salidas");
        mnuFarmacia.add(jMenuItem6);

        jMenuItem7.setText("Inventario");
        mnuFarmacia.add(jMenuItem7);

        jMenuItem8.setText("Solicitudes");
        mnuFarmacia.add(jMenuItem8);

        jMenuBar1.add(mnuFarmacia);

        mnuCtrlEnf.setText("ControlEnf");
        mnuCtrlEnf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jMenuItem9.setText("Personal");
        mnuCtrlEnf.add(jMenuItem9);

        jMenuItem10.setText("Registro de Salud");
        mnuCtrlEnf.add(jMenuItem10);

        jMenuItem11.setText("Pedido Medicamentos");
        mnuCtrlEnf.add(jMenuItem11);

        jMenuItem14.setText("Asignacion Pacientes");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        mnuCtrlEnf.add(jMenuItem14);

        jMenuBar1.add(mnuCtrlEnf);

        mnuBenefactores.setText("Benefactores");
        mnuBenefactores.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jMenuItem1.setText("Control");
        mnuBenefactores.add(jMenuItem1);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Donaciones");
        mnuBenefactores.add(jCheckBoxMenuItem1);

        jMenuBar1.add(mnuBenefactores);

        mnuInventario.setText("Inventario");
        mnuInventario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jMenuItem15.setText("Control");
        mnuInventario.add(jMenuItem15);

        jMenuBar1.add(mnuInventario);

        mnuUsuarios.setText("Usuarios");
        mnuUsuarios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        mnuUserCtrl.setText("Control");
        mnuUserCtrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUserCtrlActionPerformed(evt);
            }
        });
        mnuUsuarios.add(mnuUserCtrl);

        jMenuItem12.setText("Cambio Pwd");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        mnuUsuarios.add(jMenuItem12);

        jMenuBar1.add(mnuUsuarios);

        mnuSalir.setText("Salir");
        mnuSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jMenuItem13.setText("Salir");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        mnuSalir.add(jMenuItem13);

        jMenuBar1.add(mnuSalir);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        FrmCambioPwd fpwd = new FrmCambioPwd();
        fpwd.setVisible(true);

    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void mnuUserCtrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUserCtrlActionPerformed
         FrmUsuarios fusr = new FrmUsuarios();
         fusr.setVisible(true);
  //         this.setVisible(false);
    }//GEN-LAST:event_mnuUserCtrlActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu mnuBenefactores;
    private javax.swing.JMenu mnuCtrlEnf;
    private javax.swing.JMenu mnuFarmacia;
    private javax.swing.JMenu mnuInventario;
    private javax.swing.JMenu mnuPacientes;
    private javax.swing.JMenu mnuSalir;
    private javax.swing.JMenuItem mnuUserCtrl;
    private javax.swing.JMenu mnuUsuarios;
    // End of variables declaration//GEN-END:variables
}
