/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Pantallas;

import clases.Datos;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author joelfc
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
   private void desactivar(){
       mnuClientes.setVisible(false);
       mnuGranjas.setVisible(false);
       mnuProveedores.setVisible(false);
       mnuProduccion.setVisible(false);
       mnuParvadas.setVisible(false);
       mnuParametros.setVisible(false);
       mnuParvadas.setVisible(false);
       mnuPuestos.setVisible(false);
       smenuUsuarios.setVisible(false);
   }
    public FrmPrincipal() {
        initComponents();
        desactivar();
     
        
        lblUsuarioActual.setText(Datos.nombre);
        
        if(Datos.modClientes>0)
          mnuClientes.setVisible(true);
        if(Datos.modCompras>0)
           mnuGastos.setVisible(true);
        if(Datos.modGastos>0)
            mnuGastos.setVisible(true);
        if(Datos.modGranjas>0)
        mnuGranjas.setVisible(true);
        if(Datos.modParametros>0)
           mnuParametros.setVisible(true);
        if(Datos.modProveedores>0)
            mnuProveedores.setVisible(true);
        if(Datos.modPuestos>0)
            mnuPuestos.setVisible(true);
        if(Datos.modParvadas>0)
            mnuParvadas.setVisible(true);
        if(Datos.modUsuarios>0)
          smenuUsuarios.setVisible(true);
        
       
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FrmGranjas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(FrmGranjas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(FrmGranjas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(FrmGranjas.class.getName()).log(Level.SEVERE, null, ex);
        }
          
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblUsuarioActual = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuCatalogos = new javax.swing.JMenu();
        mnuGranjas = new javax.swing.JMenuItem();
        smenuUsuarios = new javax.swing.JMenuItem();
        mnuClientes = new javax.swing.JMenuItem();
        mnuPuestos = new javax.swing.JMenuItem();
        mnuProveedores = new javax.swing.JMenuItem();
        mnuParvadas = new javax.swing.JMenuItem();
        mnuProduccion = new javax.swing.JMenu();
        mnuEntradas = new javax.swing.JMenuItem();
        mnuSalidas = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        mnuGastos = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        mnuReportes = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        mnuParametros = new javax.swing.JMenu();
        mnuParams = new javax.swing.JMenuItem();
        frmEmpresa = new javax.swing.JMenuItem();
        mnuUsuarios = new javax.swing.JMenu();
        mnuCAmbioPwd = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setText("Sistema Avicola");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 490, 100));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 0));
        jLabel3.setText("Módulo Administrativo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, -1, -1));

        lblUsuarioActual.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblUsuarioActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 180, 20));

        jLabel4.setText("Usuario");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1050, 890));

        jMenuBar1.setAlignmentY(10.0F);
        jMenuBar1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N

        mnuCatalogos.setText("Catalogos");
        mnuCatalogos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        mnuGranjas.setText("Granjas");
        mnuGranjas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGranjasActionPerformed(evt);
            }
        });
        mnuCatalogos.add(mnuGranjas);

        smenuUsuarios.setText("Usuarios");
        smenuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smenuUsuariosActionPerformed(evt);
            }
        });
        mnuCatalogos.add(smenuUsuarios);

        mnuClientes.setText("Clientes");
        mnuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuClientesActionPerformed(evt);
            }
        });
        mnuCatalogos.add(mnuClientes);

        mnuPuestos.setText("Puestos");
        mnuPuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPuestosActionPerformed(evt);
            }
        });
        mnuCatalogos.add(mnuPuestos);

        mnuProveedores.setText("Proveedores");
        mnuProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProveedoresActionPerformed(evt);
            }
        });
        mnuCatalogos.add(mnuProveedores);

        mnuParvadas.setText("Parvadas");
        mnuParvadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuParvadasActionPerformed(evt);
            }
        });
        mnuCatalogos.add(mnuParvadas);

        jMenuBar1.add(mnuCatalogos);

        mnuProduccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mnuProduccion.setText("Produccion");
        mnuProduccion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mnuProduccion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        mnuEntradas.setText("Entradas");
        mnuEntradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEntradasActionPerformed(evt);
            }
        });
        mnuProduccion.add(mnuEntradas);

        mnuSalidas.setText("Salidas");
        mnuSalidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalidasActionPerformed(evt);
            }
        });
        mnuProduccion.add(mnuSalidas);

        jMenuItem7.setText("Inventario");
        mnuProduccion.add(jMenuItem7);

        jMenuItem8.setText("Pedidos");
        mnuProduccion.add(jMenuItem8);

        jMenuItem17.setText("Cobranza");
        mnuProduccion.add(jMenuItem17);

        jMenuBar1.add(mnuProduccion);

        mnuGastos.setText("Gastos");
        mnuGastos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jMenuItem9.setText("Fijos");
        mnuGastos.add(jMenuItem9);

        jMenuItem10.setText("Medicamentos");
        mnuGastos.add(jMenuItem10);

        jMenuItem11.setText("Pedido Medicamentos");
        mnuGastos.add(jMenuItem11);

        jMenuItem14.setText("Alimento");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        mnuGastos.add(jMenuItem14);

        jMenuBar1.add(mnuGastos);

        mnuReportes.setText("Reportes");
        mnuReportes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jMenuItem1.setText("Control");
        mnuReportes.add(jMenuItem1);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Graficas");
        mnuReportes.add(jCheckBoxMenuItem1);

        jMenuBar1.add(mnuReportes);

        mnuParametros.setText("Parametros");
        mnuParametros.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        mnuParams.setText("Control");
        mnuParams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuParamsActionPerformed(evt);
            }
        });
        mnuParametros.add(mnuParams);

        frmEmpresa.setText("Empresa");
        frmEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmEmpresaActionPerformed(evt);
            }
        });
        mnuParametros.add(frmEmpresa);

        jMenuBar1.add(mnuParametros);

        mnuUsuarios.setText("Usuarios");
        mnuUsuarios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        mnuCAmbioPwd.setText("Cambio Pwd");
        mnuCAmbioPwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCAmbioPwdActionPerformed(evt);
            }
        });
        mnuUsuarios.add(mnuCAmbioPwd);

        jMenuBar1.add(mnuUsuarios);

        mnuSalir.setText("Salir");
        mnuSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jMenuItem13.setText("Salir");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        mnuSalir.add(jMenuItem13);

        jMenuBar1.add(mnuSalir);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuClientesActionPerformed
        // TODO add your handling code here:
        FrmClientes frmc = new FrmClientes();
        frmc.setVisible(true);
    }//GEN-LAST:event_mnuClientesActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void mnuCAmbioPwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCAmbioPwdActionPerformed
        FrmCambioPwd fpwd = new FrmCambioPwd();
        fpwd.setVisible(true);

    }//GEN-LAST:event_mnuCAmbioPwdActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void mnuEntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEntradasActionPerformed
        // TODO add your handling code here:
        FrmProduccion frmp = new FrmProduccion();
        frmp.setVisible(true);
    }//GEN-LAST:event_mnuEntradasActionPerformed

    private void mnuGranjasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGranjasActionPerformed
        // TODO add your handling code here:
        FrmGranjas frmg = new FrmGranjas();
        frmg.setVisible(true);
    }//GEN-LAST:event_mnuGranjasActionPerformed

    private void mnuParvadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuParvadasActionPerformed
        // TODO add your handling code here:
       FrmParvadas par = new FrmParvadas();
       par.setVisible(true);
    }//GEN-LAST:event_mnuParvadasActionPerformed

    private void smenuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smenuUsuariosActionPerformed
        // TODO add your handling code here:
        FrmUsuarios frmu = new FrmUsuarios();
        frmu.setVisible(true);
    }//GEN-LAST:event_smenuUsuariosActionPerformed

    private void mnuPuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPuestosActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_mnuPuestosActionPerformed

    private void mnuProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProveedoresActionPerformed
        // TODO add your handling code here:
        FrmProveedores frmp = new FrmProveedores();
        frmp.setVisible(true);
    }//GEN-LAST:event_mnuProveedoresActionPerformed

    private void mnuSalidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalidasActionPerformed
        // TODO add your handling code here:
        FrmVentas frmv = new FrmVentas();
        frmv.setVisible(true);
    }//GEN-LAST:event_mnuSalidasActionPerformed

    private void frmEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmEmpresaActionPerformed
        // TODO add your handling code here:
        FrmEmpresa frme = new FrmEmpresa();
       
        frme.setVisible(true);
       
    }//GEN-LAST:event_frmEmpresaActionPerformed

    private void mnuParamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuParamsActionPerformed
        // TODO add your handling code here:
        PantConfig pc = new PantConfig();
        pc.setVisible(true);
    }//GEN-LAST:event_mnuParamsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem frmEmpresa;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JLabel lblUsuarioActual;
    private javax.swing.JMenuItem mnuCAmbioPwd;
    private javax.swing.JMenu mnuCatalogos;
    private javax.swing.JMenuItem mnuClientes;
    private javax.swing.JMenuItem mnuEntradas;
    private javax.swing.JMenu mnuGastos;
    private javax.swing.JMenuItem mnuGranjas;
    private javax.swing.JMenu mnuParametros;
    private javax.swing.JMenuItem mnuParams;
    private javax.swing.JMenuItem mnuParvadas;
    private javax.swing.JMenu mnuProduccion;
    private javax.swing.JMenuItem mnuProveedores;
    private javax.swing.JMenuItem mnuPuestos;
    private javax.swing.JMenu mnuReportes;
    private javax.swing.JMenuItem mnuSalidas;
    private javax.swing.JMenu mnuSalir;
    private javax.swing.JMenu mnuUsuarios;
    private javax.swing.JMenuItem smenuUsuarios;
    // End of variables declaration//GEN-END:variables
}
