/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Pantallas;

import clases.DaoUsuario;
import clases.Hash;

/**
 *
 * @author joelfc
 */
public class FrmUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form frmUsuarios
     */
    public FrmUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtClave = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApPaterno = new javax.swing.JTextField();
        txtApMaterno = new javax.swing.JTextField();
        chkPacientes = new javax.swing.JCheckBox();
        chkFarmacia = new javax.swing.JCheckBox();
        chkCtrlEnf = new javax.swing.JCheckBox();
        chkBenefactores = new javax.swing.JCheckBox();
        chkInventario = new javax.swing.JCheckBox();
        chkPersMed = new javax.swing.JCheckBox();
        btnAgregar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnResetPwd = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Clave");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, 30));

        txtClave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 171, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Ap. Paterno");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Ap. Materno");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, 30));

        txtNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 171, 30));

        txtApPaterno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtApPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 171, 30));

        txtApMaterno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtApMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 168, 30));

        chkPacientes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chkPacientes.setText("Pacientes");
        getContentPane().add(chkPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 281, -1, -1));

        chkFarmacia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chkFarmacia.setText("Farmacia");
        getContentPane().add(chkFarmacia, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 281, -1, -1));

        chkCtrlEnf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chkCtrlEnf.setText("Ctrl Enfermeria");
        getContentPane().add(chkCtrlEnf, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 281, -1, -1));

        chkBenefactores.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chkBenefactores.setText("Benefactores");
        getContentPane().add(chkBenefactores, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 309, -1, -1));

        chkInventario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chkInventario.setText("Inventario");
        getContentPane().add(chkInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 309, -1, -1));

        chkPersMed.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chkPersMed.setText("Personal Medico");
        getContentPane().add(chkPersMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 309, -1, -1));

        btnAgregar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 364, -1, 41));

        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 363, 72, 42));

        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 364, -1, 41));

        btnResetPwd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnResetPwd.setText("Reset Pwd");
        getContentPane().add(btnResetPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 364, -1, 41));

        btnModificar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnModificar.setText("Modificar");
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 364, -1, 41));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Control de Usuarios");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Asignar Acceso a   Módulos  ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 246, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clave", "Nombre", "Ap. Paterno", "Ap. Materno"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 410, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
       DaoUsuario du = new DaoUsuario();
       du.setClave(txtClave.getText());
       du.setPassword(Hash.sha1(txtClave.getText()+"Pwd"));
       du.setNombre(txtNombre.getText());
       du.setAppat(txtApPaterno.getText());
       du.setApmat(txtApMaterno.getText());
       
       du.setmPacientes(chkPacientes.isSelected()?1:0);
       du.setmFarmacia(chkFarmacia.isSelected()?1:0);
       du.setmCtrlEnf(chkCtrlEnf.isSelected()?1:0);
       du.setmBenefactores(chkBenefactores.isSelected()?1:0);
       du.setmInventario(chkInventario.isSelected()?1:0);
       du.setmPersMed(chkPersMed.isSelected()?1:0);
       
       du.agregar();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
      
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnResetPwd;
    private javax.swing.JButton btnSalir;
    private javax.swing.JCheckBox chkBenefactores;
    private javax.swing.JCheckBox chkCtrlEnf;
    private javax.swing.JCheckBox chkFarmacia;
    private javax.swing.JCheckBox chkInventario;
    private javax.swing.JCheckBox chkPacientes;
    private javax.swing.JCheckBox chkPersMed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtApMaterno;
    private javax.swing.JTextField txtApPaterno;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
